name: Catalog Validation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Setup dotnet-script
      run: dotnet tool install -g dotnet-script
    - name: Validate Catalog
      run: dotnet script --no-cache ./src/CatalogValidation.csx -- ./docs/Catalog.xml
